version: '3'

services:
  musicbot:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    image: musicbot
    container_name: musicbot-2
    environment:
      - TOKEN=${TOKEN}
